### ISSUE TITLE
Currency is not supported

### ISSUE THREAD

**Issue by prateek241** [Meabed/Paypal-Multi-Currency-Magento#6]
I am trying to convert INR to USD. But getting the following error.PayPal gateway has rejected request. Currency is not supported (#10605: Transaction refused because of an invalid argument. See additional error messages for details).

**Comment by prateek241** [comment]
After looking into the issue a bit, I found that in the newer versions of Magento, PayPal Standard method is activated with Express checkout. This plugin is designed for overriding standard checkout.

**Comment by meabed** [comment]
if you could work in a fix would be great :) :+1:

**Comment by KathirvelGContus** [comment]
Hi Guys, 

I have also checked into that, we are also getting the same issue "PayPal gateway has rejected request. Currency is not supported (#10605: Transaction refused because of an invalid argument. See additional error messages for details)."

I have used the same extension in 1.7 & 1.8, its was working fine. But in the 1.9.xx series is not working. Kindly share your ideas and give your ideas on this.. 

Thanks in Advance...
